import { create } from "zustand";
import { persist, createJSONStorage } from "zustand/middleware";
import type {
  ChatHistoryItem,
  FileReference,
  ProjectInfo,
  WikiStructure,
} from "../lib/api";

export interface ChatMessage {
  // Stable per-message identifier so React keys + future virtualization
  // don't collide on array-index reuse (e.g. after a retry that rewrites
  // the trailing turn). Generated by addChatMessage when omitted.
  id: string;
  role: "user" | "assistant";
  content: string;
  references?: FileReference[];
  error?: string;
  // True when the user stopped the stream mid-flight; rendered as an
  // explicit badge so it stands out from organic message endings.
  stopped?: boolean;
}

const MAX_MESSAGES_PER_PROJECT = 50;

let _msgCounter = 0;
function newMessageId(): string {
  // crypto.randomUUID isn't reliably available in older Safari, so we
  // combine a monotonic counter with Date.now to keep ids unique enough
  // for React keys without needing the crypto API.
  _msgCounter += 1;
  return `m-${Date.now().toString(36)}-${_msgCounter.toString(36)}`;
}

interface WikiStore {
  projectId: string;
  project: ProjectInfo | null;
  wiki: WikiStructure | null;
  currentPageId: string;
  scanProgress: string[];
  chatHistory: Record<string, ChatMessage[]>;
  loading: boolean;
  error: string;
  settings: { apiKey: string; model: string; language: string };

  setProjectId: (id: string) => void;
  setProject: (p: ProjectInfo) => void;
  setWiki: (w: WikiStructure) => void;
  setCurrentPage: (id: string) => void;
  addProgress: (step: string) => void;
  getMessages: (projectId: string) => ChatMessage[];
  // Caller may omit `id` -- one is auto-generated. Returns the resulting
  // id so callers can later reference the inserted message.
  addChatMessage: (projectId: string, msg: Omit<ChatMessage, "id"> & { id?: string }) => string;
  appendToLastChat: (projectId: string, text: string) => void;
  setLastChatReferences: (projectId: string, refs: FileReference[]) => void;
  setLastChatError: (projectId: string, error: string) => void;
  setLastChatStopped: (projectId: string) => void;
  truncateChatAfter: (projectId: string, messageId: string) => void;
  clearChat: (projectId: string) => void;
  setLoading: (v: boolean) => void;
  setError: (e: string) => void;
  updateSettings: (s: Partial<WikiStore["settings"]>) => void;
  reset: () => void;
}

function patchLast(
  history: Record<string, ChatMessage[]>,
  projectId: string,
  patcher: (msg: ChatMessage) => ChatMessage,
): Record<string, ChatMessage[]> {
  const msgs = history[projectId] ?? [];
  if (msgs.length === 0) return history;
  const next = msgs.slice();
  next[next.length - 1] = patcher(next[next.length - 1]);
  return { ...history, [projectId]: next };
}

export function toHistoryItems(messages: ChatMessage[]): ChatHistoryItem[] {
  // Drop the trailing empty assistant placeholder (added before streaming
  // starts) and anything without textual content.
  const out: ChatHistoryItem[] = [];
  for (const m of messages) {
    if (!m.content?.trim()) continue;
    out.push({ role: m.role, content: m.content });
  }
  return out;
}

export const useWikiStore = create<WikiStore>()(
  persist(
    (set, get) => ({
      projectId: "",
      project: null,
      wiki: null,
      currentPageId: "index",
      scanProgress: [],
      chatHistory: {},
      loading: false,
      error: "",
      settings: { apiKey: "", model: "deepseek", language: "en" },

      setProjectId: (id) => set({ projectId: id }),
      setProject: (p) => set({ project: p }),
      setWiki: (w) => set({ wiki: w }),
      setCurrentPage: (id) => set({ currentPageId: id }),
      addProgress: (step) =>
        set((s) => ({ scanProgress: [...s.scanProgress, step] })),

      getMessages: (projectId) => get().chatHistory[projectId] ?? [],

      addChatMessage: (projectId, msg) => {
        const id = msg.id ?? newMessageId();
        const stored: ChatMessage = { ...msg, id };
        set((s) => {
          const prior = s.chatHistory[projectId] ?? [];
          const next = [...prior, stored];
          // cap per-project history so localStorage doesn't grow unbounded
          const trimmed =
            next.length > MAX_MESSAGES_PER_PROJECT
              ? next.slice(-MAX_MESSAGES_PER_PROJECT)
              : next;
          return {
            chatHistory: { ...s.chatHistory, [projectId]: trimmed },
          };
        });
        return id;
      },

      appendToLastChat: (projectId, text) =>
        set((s) => ({
          chatHistory: patchLast(s.chatHistory, projectId, (m) =>
            m.role === "assistant"
              ? { ...m, content: m.content + text }
              : m,
          ),
        })),

      setLastChatReferences: (projectId, refs) =>
        set((s) => ({
          chatHistory: patchLast(s.chatHistory, projectId, (m) =>
            m.role === "assistant" ? { ...m, references: refs } : m,
          ),
        })),

      setLastChatError: (projectId, error) =>
        set((s) => ({
          chatHistory: patchLast(s.chatHistory, projectId, (m) =>
            m.role === "assistant" ? { ...m, error } : m,
          ),
        })),

      setLastChatStopped: (projectId) =>
        set((s) => ({
          chatHistory: patchLast(s.chatHistory, projectId, (m) =>
            m.role === "assistant" ? { ...m, stopped: true } : m,
          ),
        })),

      truncateChatAfter: (projectId, messageId) =>
        set((s) => {
          const msgs = s.chatHistory[projectId] ?? [];
          const idx = msgs.findIndex((m) => m.id === messageId);
          if (idx === -1) return {};
          // Keep messages up to AND including the one we're retrying from --
          // the caller will replace it / append a new turn.
          return {
            chatHistory: { ...s.chatHistory, [projectId]: msgs.slice(0, idx + 1) },
          };
        }),

      clearChat: (projectId) =>
        set((s) => {
          const next = { ...s.chatHistory };
          delete next[projectId];
          return { chatHistory: next };
        }),

      setLoading: (v) => set({ loading: v }),
      setError: (e) => set({ error: e }),
      updateSettings: (s) =>
        set((state) => ({ settings: { ...state.settings, ...s } })),
      reset: () =>
        set({
          projectId: "",
          project: null,
          wiki: null,
          currentPageId: "index",
          scanProgress: [],
          loading: false,
          error: "",
        }),
    }),
    {
      name: "repowiki-store",
      // chat history lives across tab reloads and browser restarts; the
      // wider Zustand persist machinery still uses sessionStorage for
      // ephemeral fields, but the parts we care about ride localStorage.
      storage: createJSONStorage(() => localStorage),
      partialize: (state) => ({
        projectId: state.projectId,
        settings: state.settings,
        chatHistory: state.chatHistory,
      }),
    },
  ),
);
